development:
  host: localhost
  database: rails3_mongoid_devise_development

test:
  host: localhost
  database: rails3_mongoid_devise_test

# set these environment variables on your prod server
production:
  uri: <%= "mongodb://sharan:sharan@dbh85.mongolab.com:27857/heroku_app13666229" %>
  # slaves:
  #   - host: slave1.local
  #     port: 27018
  #   - host: slave2.local
  #     port: 27019
